### PR TITLE
Properly paginate runner lists call.

### LINKED ISSUE #46: Action not detecting registered runners.
Hi,

About ~10 hours ago our build started failing with the [timeout error](https://github.com/airbytehq/airbyte/runs/2760497061?check_suite_focus=true) out of the blue; I double checked and made sure no infrastructure or code changes were made.

I also tried upgrading from 2.1.0 to 2.2.0 to no effect.

I confirmed networking is working fine by manually creating an instance with the same networking set up and running the same commands the action [runs](https://github.com/machulav/ec2-github-runner/blob/main/src/aws.js#L11). I was able to register a runner with Github.

I observed the runner page and saw that that runners were coming up and being registered fine. They were sitting in Idle while the action was polling for them. This screen shot shows my test instance, as well as the two self hosted instances our build runs usually start up before they are terminated after the 5 min window.
Screen Shot 2021-06-07 at 12 20 11 PM

Has anyone else observed this in the last day or two? Any ideas how to proceed with this?
 
Thanks!

### PR DESCRIPTION
**Pull request by davinchia**
Use the octokit [paginate](https://octokit.github.io/rest.js/v18#pagination) to properly paginate the list call. This fixes #46.

### CODE REVIEW

**Comment by davinchia** [comment]
@machulav I don't see any tests here. Let me know what kind of tests I should figure out as part of this PR.

**Review by jaredmdobson — APPROVED** [review]

**Comment by davinchia** [comment]
@jaredmdobson any idea what it would take to merge this in? I'm very eager to use this in our builds!

**Comment by machulav** [comment]
@davinchia, many thanks for your contribution and sorry for the late reply. I've merged your PR to master so that you can use it from the master branch for now. A bit later, I will make a new version with this fix.

**Comment by davinchia** [comment]
Thanks @machulav ! What action version do I specify to use the version at master?

**Comment by machulav** [comment]
@davinchia For now, you can use `machulav/ec2-github-runner@master` as a value of `uses`. It will take the sources from the master branch.

**Comment by davinchia** [comment]
thank you @machulav  - please let me know when you do a new release!

**Comment by machulav** [comment]
@davinchia I've added a new version [v2.2.1](https://github.com/machulav/ec2-github-runner/releases/tag/v2.2.1) that contains your fix. In addition, I've added a version [v2](https://github.com/machulav/ec2-github-runner/releases/tag/v2) which tracks the latest v2.x.x release. So you can use now `machulav/ec2-github-runner@v2` and you will receive all the latest backward-compatible updates.

Than you again for the contribution! 🙏

**Pull request merged**
