### PR TITLE
add docker to github user

### PR DESCRIPTION
**Pull request by lielran**

### CODE REVIEW

**Comment by machulav** [comment]
@lielran, thank you for your PR! It really makes sense here as I also recently noticed that the Docker container actions don't run on the self-hosted runner as Docker is not installed there by default.

**Comment by lielran** [comment]
close this for now since it wasn't working for me :/

**Comment by machulav** [comment]
@lielran  Can you please specify what exactly doesn't work for you?

**Comment by lielran** [comment]
> @lielran Can you please specify what exactly doesn't work for you?

yes, sure. 

I've tried multiple ways to install docker and use it within the runner. 
first via the step - require sudo
then via user-input(run as root on the machine startup) - this works, I was able to install docker and add github user to the docker group, but I failed to use a docker step. probably because the machine needs to be restart after the installation(a normal reconnect ssh session usually solved that). 

I created a custom image (base on amazon linux v2) with docker installed but end up with the same issues when trying to run `docker info`

**Comment by machulav** [comment]
Thank you for the helpful information!

**Pull request closed without merging**
