### PR TITLE
fix: `invalid culture identifier`

### PR DESCRIPTION
**Pull request by skyzh**
After GitHub bumps .NET version of actions runner, our EC2 runner reports:

```
System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at System.Globalization.CultureInfo..ctor(String name)
   at GitHub.Runner.Common.HostContext.SetDefaultCulture(String name)
   at GitHub.Runner.Worker.Worker.SetCulture(AgentJobRequestMessage message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```

And from this issue https://github.com/actions/runner/issues/1605, it seems that we should remove `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT`.

I'm still testing with this change, not sure if this really works. Thanks for reviewing!

### CODE REVIEW

**Comment by davinchia** [comment]
@skyzh we are running into this as well - pls keep me updated.

**Comment by skyzh** [comment]
Hi @davinchia, my forked action works perfectly in our environment. To use it for now, simply apply the following snippet in the GitHub Action config.

```
uses: skyzh/ec2-github-runner@ba2298a67875dfdd29a88fafbc1ba27f4f94af39
```

After this PR gets merged, or GitHub staff reverts the action .NET runtime, you can change back to `machulav/ec2-github-runner@v2`.

**Comment by davinchia** [comment]
amazing, let me give it a shot

**Comment by davinchia** [comment]
@skyzh works for us - thanks so much again!

**Comment by skyzh** [comment]
Hi @machulav, would you please take a look if you have time? Thanks!

**Comment by IceTDrinker** [comment]
it this action still getting support/being developed ?

**Comment by machulav** [comment]
Let me make some final tests and I will merge if everything works.

**Comment by machulav** [comment]
Merged. The `machulav/ec2-github-runner@v2` already contains the fix.

@skyzh @ramosbugs thanks a lot for figuring that out and for the fix!

**Pull request merged**
